apiVersion: v1
kind: Service
metadata:
  name: gitea-postgresql
  namespace: gitea
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/component: primary
