apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      securityContext:
        fsGroup: 1000
      ##  runAsUser: 1000
      ##  runAsGroup: 1000
      containers:
      - name: gitea
        image: gitea/gitea:latest
        env:
          - name: SSH_LISTEN_PORT
            value: "22"
          - name: SSH_PORT
            value: "22"
          - name: GITEA_APP_INI
            value: /data/gitea/conf/app.ini
          - name: GITEA_CUSTOM
            value: /data/gitea
          - name: GITEA_WORK_DIR
            value: /data
          - name: GITEA_TEMP
            value: /tmp/gitea
          - name: TMPDIR
            value: /tmp/gitea
        ports:
        - containerPort: 3000
          name: gitea
        - containerPort: 22
          name: git-ssh
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #     - ALL
        #     add:
        #     - SYS_CHROOT
        #   privileged: false
        #   readOnlyRootFilesystem: true
        #   runAsUser: 1000
        #   runAsNonRoot: true
        #   runAsGroup: 1000
        volumeMounts:
        - name: temp
          mountPath: /tmp
        - name: data
          mountPath: /data
      volumes:
      - name: temp
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: gitea
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
