apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /generate-values
  name: generate-values
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|generate-values
source: |-
  load("krmfn.star", "krmfn")
  def set_values(resources):
    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "kptfile.kpt.dev"):
        clusterName = r["data"].get("clusterName", "default")
        name = r["data"]["name"]
    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "localconfig"):
        clusterName = r["data"].get("clusterName", "default")
        name = r["data"]["name"]
    for r in resources:
      if krmfn.match_gvk(r, "infra.nephio.org/v1alpha1", "Repository"):
        r["metadata"]["name"] = clusterName
        r["spec"]["description"] = clusterName + " repository"
      if krmfn.match_gvk(r, "config.porch.kpt.dev/v1alpha1", "Repository"):
        r["metadata"]["name"] = clusterName
        r["spec"]["git"]["repo"] = "http://172.18.0.200:3000/nephio/" + clusterName + ".git"
        r["spec"]["git"]["secretRef"]["name"] = clusterName + "-access-token-porch"
        if clusterName == "mgmt-staging":
           r["spec"]["deployment"] = False
           r["metadata"]["annotations"]["nephio.org/staging"] = "true"
      if krmfn.match_gvk(r, "infra.nephio.org/v1alpha1", "Token"):
        r["metadata"]["name"] = clusterName + "-access-token-porch"
        if "annotations" in r["metadata"] and "nephio.org/app" in r["metadata"]["annotations"] and "configsync" in r["metadata"]["annotations"]["nephio.org/app"]:
          r["metadata"]["name"] = clusterName + "-access-token-configsync"
          if clusterName == "mgmt" or clusterName == "mgmt-staging":
            r["metadata"]["namespace"] = "config-management-system"
  set_values(ctx.resource_list["items"])
