apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: network-config
    app.kubernetes.io/part-of: network-config
    app.kubernetes.io/version: tbd
  name: network-config-controller-target-role
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inv.nephio.org
  resources:
  - targets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - inv.nephio.org
  resources:
  - targets/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
