apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /porch-controllers-packagevariantsets
  creationTimestamp: null
  name: porch-controllers-packagevariantsets
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|porch-controllers-packagevariantsets'
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariantsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariantsets/finalizers
  verbs:
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariantsets/status
  verbs:
  - get
  - patch
  - update
