apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n2
  annotations:
    nephio.org/network-name: n2
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: apps/v1.Deployment.ueransimgnb-example
    specializer.nephio.org/namespace: example
spec:
  networkInstance:
    name: vpc-ran
  cniType: macvlan
  attachmentType: vlan
