apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: vpc-ran
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  topology: nephio
  routingTables:
  - name: vpc-ran
    prefixes:
    - prefix: 172:2::/32
      labels:
        nephio.org/network-name: n2
    - prefix: 172.2.0.0/16
      labels:
        nephio.org/network-name: n2
    - prefix: 172:3::/32
      labels:
        nephio.org/network-name: n3
    - prefix: 172.3.0.0/16
      labels:
        nephio.org/network-name: n3
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-ran 
  bridgeDomains: 
  - name: vpc-ran
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: vlan