apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: workload-cluster
  annotations:
    config.kubernetes.io/local-config: "true"
    kpt.dev/config-injection: required
spec:
  clusterName: example