apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-configsync
spec:
  upstream:
    package: nephio-configsync
    repo: blueprint-manifests
    revision: main
  downstream:
    package: example-configsync
    repo: mgmt-staging
  packageContext:
    data:
      clusterName: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example